local resources = {
	graphics = {
		caustics = {
			'caustics/caustic00.jpg',
			'caustics/caustic01.jpg',
			'caustics/caustic02.jpg',
			'caustics/caustic03.jpg',
			'caustics/caustic04.jpg',
			'caustics/caustic05.jpg',
			'caustics/caustic06.jpg',
			'caustics/caustic07.jpg',
			'caustics/caustic08.jpg',
			'caustics/caustic09.jpg',
			'caustics/caustic10.jpg',
			'caustics/caustic11.jpg',
			'caustics/caustic12.jpg',
			'caustics/caustic13.jpg',
			'caustics/caustic14.jpg',
			'caustics/caustic15.jpg',
			'caustics/caustic16.jpg',
			'caustics/caustic17.jpg',
			'caustics/caustic18.jpg',
			'caustics/caustic19.jpg',
			'caustics/caustic20.jpg',
			'caustics/caustic21.jpg',
			'caustics/caustic22.jpg',
			'caustics/caustic23.jpg',
			'caustics/caustic24.jpg',
			'caustics/caustic25.jpg',
			'caustics/caustic26.jpg',
			'caustics/caustic27.jpg',
			'caustics/caustic28.jpg',
			'caustics/caustic29.jpg',
			'caustics/caustic30.jpg',
			'caustics/caustic31.jpg',
		},
		smoke = {
			'smoke/smoke00.tga',
			'smoke/smoke01.tga',
			'smoke/smoke02.tga',
			'smoke/smoke03.tga',
			'smoke/smoke04.tga',
			'smoke/smoke05.tga',
			'smoke/smoke06.tga',
			'smoke/smoke07.tga',
			'smoke/smoke08.tga',
			'smoke/smoke09.tga',
			'smoke/smoke10.tga',
			'smoke/smoke11.tga',
		},
		scars = {
			'scars/scar1.bmp',
			'scars/scar2.bmp',
			'scars/scar3.bmp',
			'scars/scar4.bmp',
		},
		trees = {
			bark = 'Bark.bmp',
			leaf = 'bleaf.bmp',
			gran1 = 'gran.bmp',
			gran2 = 'gran2.bmp',
			birch1 = 'birch1.bmp',
			birch2 = 'birch2.bmp',
			birch3 = 'birch3.bmp',
		},
		maps = {
			detailtex = 'detailtex2.bmp',
			watertex = 'ocean.jpg',
		},
		groundfx = {
			groundflash = 'groundflash.tga',
			groundring = 'groundring.tga',
			seismic = 'circles.tga',
		},
		projectiletextures = {
				--custom made
			wake = 'fx/wake.tga',
			holoproj = 'fx/holoproj.tga',
			exhaust = 'fx/exhaust.tga',
			electric1 = 'fx/electric1.tga',
			conctrail = 'fx/conctrail.tga',

				--quantum
			plasma2 = 'quantum/plasma2.tga',
			flowerflash = 'quantum/flowerflash.tga',

				--stolen from gundam
			flashside1 = 'smoth/flashside1.tga',
			uglynovaexplo = 'smoth/uglynovaexplo.tga',
			flare = 'smoth/flare.tga',
			gunshot = 'smoth/gunshot.tga',
			tibanna = 'tibanna.png',
			dirt = 'dirt.png',
			
			-- Evil4Zerggin
			---- PD
			splashside = 'splashside.tga',
			splashbase = 'splashbase.tga',
			smokesmall = 'smokesmall.tga',
			lightning = 'lightning.tga',
			lightning_white = 'lightning_white.tga',
			lightning_ball = 'lightning_ball.tga',
			fireball = 'fireball.tga',
			---- smoth's?
			burn = 'smoth/burn.tga',
			fireyexplo = 'smoth/fireyexplo.tga',
			----quantum's?
			------CC
			blueexplo = 'quantum/blueexplo.tga',
			brightblueexplo = 'quantum/brightblueexplo.tga',
			purpleexplo = 'quantum/purpleexplo.tga',
			------PD
			debris = 'quantum/debris.tga',
			debris2 = 'quantum/debris2.tga',
			
			------PD
			explosion1_01 = 'quantum/explosion1/0001.tga',
			explosion1_02 = 'quantum/explosion1/0002.tga',
			explosion1_03 = 'quantum/explosion1/0003.tga',
			explosion1_04 = 'quantum/explosion1/0004.tga',
			explosion1_05 = 'quantum/explosion1/0005.tga',
			explosion1_06 = 'quantum/explosion1/0006.tga',
			explosion1_07 = 'quantum/explosion1/0007.tga',
			explosion1_08 = 'quantum/explosion1/0008.tga',
			explosion1_09 = 'quantum/explosion1/0009.tga',
			explosion1_10 = 'quantum/explosion1/0010.tga',
			explosion1_11 = 'quantum/explosion1/0011.tga',
			explosion1_12 = 'quantum/explosion1/0012.tga',
			explosion1_13 = 'quantum/explosion1/0013.tga',
			explosion1_14 = 'quantum/explosion1/0014.tga',
			explosion1_15 = 'quantum/explosion1/0015.tga',
			explosion1_16 = 'quantum/explosion1/0016.tga',
			explosion1_17 = 'quantum/explosion1/0017.tga',
			explosion1_18 = 'quantum/explosion1/0018.tga',
			explosion1_19 = 'quantum/explosion1/0019.tga',
			explosion1_20 = 'quantum/explosion1/0020.tga',
			explosion1_21 = 'quantum/explosion1/0021.tga',
			explosion1_22 = 'quantum/explosion1/0022.tga',
			explosion1_23 = 'quantum/explosion1/0023.tga',
			explosion1_24 = 'quantum/explosion1/0024.tga',
			explosion1_25 = 'quantum/explosion1/0025.tga',
			explosion1_26 = 'quantum/explosion1/0026.tga',
			explosion1_27 = 'quantum/explosion1/0027.tga',
			
			------GPL
			explosion2_01 = 'quantum/explosion2/0001.tga',
			explosion2_02 = 'quantum/explosion2/0002.tga',
			explosion2_03 = 'quantum/explosion2/0003.tga',
			explosion2_04 = 'quantum/explosion2/0004.tga',
			explosion2_05 = 'quantum/explosion2/0005.tga',
			explosion2_06 = 'quantum/explosion2/0006.tga',
			explosion2_07 = 'quantum/explosion2/0007.tga',
			explosion2_08 = 'quantum/explosion2/0008.tga',
			explosion2_09 = 'quantum/explosion2/0009.tga',
			explosion2_10 = 'quantum/explosion2/0010.tga',
			
			------GPL
			explosion3_01 = 'quantum/explosion3/0001.png',
			explosion3_02 = 'quantum/explosion3/0002.png',
			explosion3_03 = 'quantum/explosion3/0003.png',

				--null
			blank = 'fx/null.tga',
			laserfalloff = 'fx/null.tga',
			muzzleside = 'fx/null.tga',
			muzzlefront = 'fx/null.tga',
   			fireballflaretexture = 'fx/null.tga',
			flareprojectiletexture = 'fx/null.tga',
  			missiletrailtexture = 'fx/null.tga',
			muzzleflametexture = 'fx/null.tga',
			repulsetexture = 'fx/null.tga',
			sbflaretexture = 'fx/null.tga',
			missileflaretexture = 'fx/null.tga',
			beamlaserflaretexture = 'fx/null.tga',
			sbtrailtexture = 'fx/null.tga',
			bubbletexture = 'fx/null.tga',
			gfxtexture = 'fx/null.tga',
			projectiletexture = 'fx/null.tga',



				--NO ALPHA CHANNELS
			ExplodeHeat = 'ExplodeHeat.tga',
			laserend = 'laserend.tga',
			largebeam = 'largelaserfalloff.tga',
			FragmentPlasma = 'FragmentPlasma.tga',
			MegaFlare_NoAlpha = 'MegaFlare_NoAlpha.tga',

				--SPACED BEAMBOLTS
			["001_beambolt_spacer"] = '001_beambolt_spacer.tga',
			["002_fancy_plasmabolt"] = '002_fancy_plasmabolt.tga',	
			["003_beambolt_spacer03"] = '003_beambolt_spacer.tga',		
			["004_BlasterBolt"] = '004_BlasterBolt.tga',
			["005_beambolt_spacer05"] = '005_beambolt_spacer.tga',

				--ALPHA CHANNELS
			Dirt001 = 'Dirt001.tga',
			Dirt002 = 'Dirt002.tga',
			Dirt003 = 'Dirt003.tga',
			plasmaball = 'plasmaball.tga',
			spikes = 'spikes.tga',
			circularthingy = 'circularthingy.tga',
			explo = 'explo.tga',
			explofade = 'explo.tga',
			randdots = 'randdots.tga',
			smoketrail = 'smoketrail.tga',
			flame = 'flame.tga',
			Gas = 'gas.tga',
			GenericSmokeCloud = 'GenericSmokeCloud.tga',
			AnotherGenericSmokeCloud = 'AnotherGenericSmokeCloud.tga',
			GenericFireBall = 'GenericFireBall.tga',
			ConeFragments = 'ConeFragments.tga',
			Fire = 'Fire.tga',
			DynamicFake = 'DynamicFake.tga',
			MegaFlare = 'MegaFlare.tga',
			small_muzzle_side = 'small_muzzle_side.tga',
			small_muzzle_back = 'small_muzzle_back.tga',

				--UNUSED DEFAULTS
			repulsegfxtexture = 'lightning_flat.tga',
			sphereparttexture = 'lightning_flat.tga',
			wrecktexture = 'fx/null.tga',
			dguntexture = 'fx/null.tga',
			
			
		},
	}
}

return resources